name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

  
      - name: Restore app
        run: dotnet restore app/app.csproj

      - name: Restore tests
        run: dotnet restore app.test/app.test.csproj

      - name: Build app
        run: dotnet build app/app.csproj -c Release --no-restore

      - name: Run tests
        run: dotnet test app.test/app.test.csproj -c Release --logger "trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"
